Vagrant.configure("2") do |config|
  config.vm.hostname = "dockerhost"
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: "192.168.51.10"
  config.omnibus.chef_version = :latest

  config.vm.define "dockerhost" do |machine|
    
    machine.vm.synced_folder ".", "/vagrant", :disabled => false, :nfs => true, :windows__nfs_options => ["-exec"]

    machine.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["vagrant/cookbooks", "Vagrant/chef/applications"]
      chef.roles_path = "vagrant/chef/roles"
      chef.add_role "docker"      
    end

    machine.vm.provider :virtualbox do |vb, override|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      override.vm.box = "trusty64"
      override.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    end

    machine.vm.provider "parallels" do |v, override|
      override.vm.box = "parallels/ubuntu-14.04"
      v.name = "vagrant_docker_host"
      v.update_guest_tools = true
      v.optimize_power_consumption = false
      v.memory = 1024
      v.cpus = 2
    end

  end
end